#                  Numpy

#    Importing numpy


In [2]:
import numpy as np
import pandas as pd

# The basics

In [6]:
a=np.array([1,2,3])                #1-D array
print(a)

[1 2 3]


In [10]:
b=np.array([[1,2,3,4] ,               #2-D array
          [5,6,7,8]])  

print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
#get dimenssion of the array

n1 = a.ndim

n2 = b.ndim

print(n1,n2)

1 2


In [17]:
# get shape (this only gives the total row and column of the array )

print(a.shape) # only shows the column part in 1-D array
print(b.shape)

(3,)
(2, 4)


In [18]:
# get data-type
b.dtype

dtype('int32')

In [25]:
#we could change the default data type stored in the array

c=np.array(a,dtype='float16')
print(a.dtype,c.dtype)

int32 float16


In [29]:
#get size

print(c.size)  #this gives the total number of the elements present in the numpy array

print(c.itemsize)  # this gives the total byte size of the numpy array 
print(b.itemsize)

3
2
4


# Accessing / Changing specific elements , rows , colums , etc .

In [33]:
d=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)  # 2 X 7 dimemenssion array .

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
#getting a specific element arr[r1,c1]

print(d[1,5])  #accessing elements

13


In [44]:
## get a specific row
print(d[0,:])  #accessing a specific row

print(d[:,2])  #accessing a specific column



[1 2 3 4 5 6 7]
[ 3 10]


In [49]:
#accesing more elements with step_count -> [start_index , end_index: step_count]
print(d[0,1:6:2])

[2 4 6]


In [56]:
d[1,0]=20  # changing the specific elements
print(d)

print()
#entire row or column

d[:,1]=500 #entire column
print(d)
print()
d[0,:]=101 #entire row
print(d)

[[101 101 101 101 101 101 101]
 [ 20 500  10  11  12  13  14]]

[[101 500 101 101 101 101 101]
 [ 20 500  10  11  12  13  14]]

[[101 101 101 101 101 101 101]
 [ 20 500  10  11  12  13  14]]


In [64]:
# 3-D array

e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
e

e[0,0:2,0:2]   # same propeties as the 1-D / 2-D arrays just three parameters are there .

array([[1, 2],
       [3, 4]])

# Initialize different types of arrays

In [70]:
# all zeros matrix

a=np.zeros(5) # 1-D array initialized with zeros
print(a)

print()

b=np.zeros([2,2,3])  # 3-d array inoitialisation with zeros
print(b)

[0. 0. 0. 0. 0.]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [73]:
#all 1's matrix

a=np.ones(5) # 1-D array initialized with ones
print(a)

print()

b=np.ones([2,2,3])  # 3-d array inoitialisation with ones
print(b)

[1. 1. 1. 1. 1.]

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [77]:
#All other numbers
a=np.full((5,5) ,100,dtype='float16') #any dimension array can be initialized with any value

print(a)


[[100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100.]]


In [80]:
# Any other numbers (full_like)
a=np.full_like(b,4)
a

array([[[4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.]]])

In [90]:
#initialize array with random array element numbers any dimensions 

a=np.random.rand(4,2,3)
print(a)

print()
b=np.random.rand(c.size)
print(b)

[[[0.3544572  0.91725425 0.24985157]
  [0.50571646 0.98174593 0.71073913]]

 [[0.98546768 0.69129148 0.49815973]
  [0.39501321 0.72422818 0.06860095]]

 [[0.38338578 0.7723791  0.11618251]
  [0.20298606 0.12596367 0.86555963]]

 [[0.29198553 0.48313631 0.40098303]
  [0.12909517 0.44939929 0.32664427]]]

[0.4845397  0.48347204 0.78792964 0.97309926 0.02207431]


In [101]:
#Random Integer values
f=np.random.randint(5,8 , size=(3,3))  #every thing same as the random decimal part just shown above
print(f)    #the (5->inclusize,8->exclusive,size of the ,mattrix) 

[[5 5 7]
 [6 6 6]
 [6 7 5]]


In [105]:
#identity matrix->n size array ->(n*n) size array and all the digonal elements will be same

a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [115]:
#repeating array

arr=np.array([[1,2,3],[4,5,6]])
r1=np.repeat(arr,3,axis=0)   #axis =0 ->represents->row , axis =1 ->represents -> column
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [130]:
#initialize 
g=np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print(g)

print()
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
print()
output[1:4,1:4]=z
output=np.array(output,dtype='int16')
print(output)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Copying

In [137]:
a=np.array([1,2,3])
b=a.copy()
b  #direct copying from a

array([1, 2, 3])

In [141]:
b[1]=100
print(b)
print(a)


[  1 100   3]
[1 2 3]


# Mathematics

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [144]:
#sum

c=a+b
c


array([ 6,  8, 10, 12])

In [146]:
#substract

c=a-b
c


array([-4, -4, -4, -4])

In [148]:
#multiply
c=a*b
c



array([ 5, 12, 21, 32])

In [151]:
#divide
c=a/2
print(c)
c=a/b
print(c)

[0.5 1.  1.5 2. ]
[0.2        0.33333333 0.42857143 0.5       ]


In [153]:
#power
c=a**b
print(c)

[    1    64  2187 65536]


In [156]:
#sin(x)

c=np.sin(a)
print(c)


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [159]:
#cos(x)

c=np.cos(a)
print(c)



[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [161]:
#etc, all other sec,cot,tan,etc function are saome as these are implemented 

# Linear alzebra

In [173]:
a =np.full((2,3),1)
print(a)
                              #column of the 1st matriz should be equal to the the 2nd matrix row
print()
b=np.full((3,2),2)
print(b)

print()

c=np.matmul(a,b)    #matrix multiplication
print(c)


[[1 1 1]
 [1 1 1]]

[[2 2]
 [2 2]
 [2 2]]

[[6 6]
 [6 6]]


In [178]:
#determinant of a matrix  ->help in finding the invere and transpose of a matrix

a=np.array([[6,1,1],[4,-2,5],[2,8,7]],dtype='int16')
c=np.linalg.det(a)
c=int(c)
print(c)

-306


In [180]:
#refer to Keith link for more functions on the linearalzebra

# Statistics

In [182]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
#min
np.min(stats)

1

In [186]:
#max
np.max(stats)

6

In [188]:
#sum of all elements
np.sum(stats)

21

In [190]:
#for more refer to the numpy documentations

# Rorganizing Arrays

In [194]:
#reshaping the array

before=np.array([[1,2,3,4],[5,6,7,8]])
print(before,before.shape)


print()

after= before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [197]:
#vertiacally stacking vectors / matrixes

v1=np.array([1,2,3,4,5])
v2=np.array([6,7,8,9,10])

v3=np.vstack([v1,v2])
print(v3)   #merge two araay together but needs to have same dimenssions

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [199]:
#horizontal stacking :-


v1=np.array([1,2,3,4,5])
v2=np.array([6,7,8,9,10])

v3=np.hstack([v1,v2])
print(v3)

[ 1  2  3  4  5  6  7  8  9 10]


# Miscellaneous 

# load data from the file (without using pandas)

In [211]:
a=pd.open("C:\Users\rohit\OneDrive\Desktop\datas.txt")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (Temp/ipykernel_15184/3701709008.py, line 1)